### ISSUE TITLE
Поиск книги

### ISSUE THREAD

**Issue by evgeniikotliarov** [Kazakbay/esdp-2016-4#24]
Чтобы поиск книги, был более простым, понятным и быстрым. Установим гем Searchkick. Чем хорош Searchkick - это гибкость и простота в использовании. Добавление информации в индекс и поиск по индексу производятся с помощью простых HTTP запросов. Так же настроим живой поиск книги по названию, либо по автору произведения, что еще более упрощает задачу поиска нужной, желаемой для прочтения книги.
Пользователь заходя на страницу поиска в библиотеке книг, вводит первые буквы названия книги, либо автора книги и в поле поиска открывается окошко, с готовыми, полными вариантами названия книг, начинающиеся именно на вводимые буквы. Если их несколько, то показываются первые пять книг в алфавитном порядке. Таким образом, пользователь может просто нажать на нужное название книги и она откроется на странице. Это очень удобно для пользователя при поиске книги, потому что позволяет не вводить полное название произведения, а выбрать из предложенных вариантов, только одним  нажатием кнопки "Enter". 
Время отведенное на изучение подключения гема  16 часов.
Время отведенное на подключение и настройку параметров поиска 16 часов.
Итого 32 часа.

**Comment by AzamatJumabekov** [comment]
Гем Searchkick установлен. Поиск книги по названию и автору работает. Необходимо реализовать живой поиск.

**Comment by evgeniikotliarov** [comment]
Живой поиск работает. Необходимо сверстать поле ввода и поле готовых результатов поиска на главной странице. Чтобы было удобно пользоваться поиском.

**Comment by evgeniikotliarov** [comment]
Все подключено, работает.
