### ISSUE TITLE
Создать таблицу комментариев.

### ISSUE THREAD

**Issue by Kazakbay** [Kazakbay/esdp-2016-4#6]
Создать таблицу комментариев. Таблица создается после того как будет создана таблица  "Книги" и "Пользователи". Сделать связь таблицы комментариев с таблицей книг и с таблицей пользователей.
1. В поле content поставить ограничение 250 символов

**Comment by evgeniikotliarov** [comment]
При связывании сущности комментарии, возник конфликт. Так как active_admin имеет свою таблицу комментариев. Необходимо переделать модель комментариев, к примеру user_comment.

**Comment by Kazakbay** [comment]
Название таблицы "сomment" изменено на "user_comment"
